### ISSUE TITLE
Weather alert overlap

### ISSUE THREAD

**Issue by Friskzips** [Test-Account666/LethalCompany-AnnounceMoonAndWeatherChange#1]
Hi, I wanted to ask if you could remove the weather alert of the moon where you were when changing a moon, so it doesn't overlap with another alert if it shows a weather alert when you get back in orbit and then you route really fast to another moon that has a weather.

**Comment by Test-Account666** [comment]
Remove the first alert when the second alert comes in?

I guess I could do that, but not finishing the sliding animation sounds a little infuriating

**Comment by Friskzips** [comment]
umm, it could be a config because I am playing with a mod that every time you get in orbit, it routes automatically to another planet, and then the alert gets overlapped if the moon before and the moon we are routing both have a weather, or it shows the alert for the moon before if it has a weather, and its kind of annoying.

**Comment by Test-Account666** [comment]
Closing this as there is a solution for this in the latest version
